SRC = main.cpp Bureaucrat.cpp AForm.cpp \
		PresidentialPardonForm.cpp \
		RobotomyRequestForm.cpp ShrubberyCreationForm.cpp \
		Intern.cpp \

NAME = Bureaucrat

all:
	g++ -Wall -Wextra -Werror -std=c++98 ${SRC} -o ${NAME}

clean:
	rm -rf ${NAME}