CC			= gcc
CFLAGS		= -Wall -Wextra -Werror -I.
BUFFER		= -D BUFFER_SIZE=5

printf:
	${CC} ${CFLAGS} ex03_ft_printf.c -o ft_printf

gnl:
	${CC} ${CFLAGS} ${BUFFER} ex03_get_next_line.c -o get_next_line
