version: '3'
services:
  mariadb:
    image: mariadb:user
    container_name: mariadb
    build: ./mariadb/
    volumes:
      - mariadb:/var/lib/mysql
    # ports:
    #   - 3306:3306
    env_file:
      - .env
    networks:
      - inception
    restart: always

  wordpress:
    image: wordpress:user
    container_name: wordpress
    build: ./wordpress/
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - 9000:9000
    depends_on:
     - mariadb
    env_file:
     - .env
    networks:
     - inception
    restart: always

  nginx:
    image: nginx:user
    container_name: nginx
    build: ./nginx/
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jteoh/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jteoh/data/wordpress

networks:
  inception:
    name: Inception
