version: '3'
services:
  mariadb:
    container_name: mariadb
    build: ./mariadb/
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: on-failure
  wordpress:
    container_name: wordpress
    build: ./wordpress/
    volumes:
      - /data/html:/var/www/html
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
      WORDPRESS_DB_NAME: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mysql
    restart: on-failure
  nginx:
    container_name: nginx
    build: ./nginx/
    volumes:
      - /data/html:/var/www/html
    ports:
      - 8080:80
    links:
      - wordpress
    restart: on-failure
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data
