#include "ClapTrap.hpp"

int	main()
{
	std::string	target = "Arnold";
	ClapTrap	A("ClapTrap");
	ClapTrap	B(A);
	ClapTrap	C;

	C = B;
	A.attack(target);
	B.attack(target);
	C.attack(target);
	A.takeDamage(50);
	B.takeDamage(1);
	C.takeDamage(1);
	A.beRepaired(1);
	B.beRepaired(1);
	C.beRepaired(1);
	A.attack(target);
	B.attack(target);
	C.attack(target);
	A.takeDamage(50);
	B.takeDamage(1);
	C.takeDamage(1);
	A.beRepaired(1);
	B.beRepaired(1);
	C.beRepaired(1);
	A.attack(target);
	B.attack(target);
	C.attack(target);
	A.takeDamage(50);
	B.takeDamage(1);
	C.takeDamage(1);
	A.beRepaired(1);
	B.beRepaired(1);
	C.beRepaired(1);
	A.attack(target);
	B.attack(target);
	C.attack(target);
	A.takeDamage(50);
	B.takeDamage(1);
	C.takeDamage(1);
	A.beRepaired(1);
	B.beRepaired(1);
	C.beRepaired(1);
	A.attack(target);
	B.attack(target);
	C.attack(target);
	A.takeDamage(50);
	B.takeDamage(1);
	C.takeDamage(1);
	A.beRepaired(1);
	B.beRepaired(1);
	C.beRepaired(1);
	A.attack(target);
	B.attack(target);
	C.attack(target);
	A.takeDamage(50);
	B.takeDamage(1);
	C.takeDamage(1);
	A.beRepaired(1);
	B.beRepaired(1);
	C.beRepaired(1);
	A.attack(target);
	B.attack(target);
	C.attack(target);
	A.takeDamage(50);
	B.takeDamage(1);
	C.takeDamage(1);
	A.beRepaired(1);
	B.beRepaired(1);
	C.beRepaired(1);
	A.attack(target);
	B.attack(target);
	C.attack(target);
	A.takeDamage(50);
	B.takeDamage(1);
	C.takeDamage(1);
	A.beRepaired(1);
	B.beRepaired(1);
	C.beRepaired(1);
	A.attack(target);
	B.attack(target);
	C.attack(target);
	A.takeDamage(50);
	B.takeDamage(1);
	C.takeDamage(1);
	A.beRepaired(1);
	B.beRepaired(1);
	C.beRepaired(1);
}
